### ISSUE TITLE
Auto-add github resources

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#185]
Similar to the [automatic intake of meta-data from zenodo](https://github.com/NFDI4BIOIMAGE/training/blob/main/scripts/auto-add-zenodo-entry.py), we may want to have this for github-resources. The [python github-API](https://github.com/PyGithub/PyGithub) might be useful for this.

If a new issue is created, and the body is only a github link, we could read the meta data of the repository and send a pull-request to add it to our list of resource.

**Comment by SeverusYixin** [comment]
That was so funny, I can try it. Can you explain it in more detail, e.g. what kind of metadata we need?

**Comment by haesleinhuepf** [comment]
Well, if you search for github repositories in our yml file, you should get an idea what kind of meta data we store currently. Not sure if all of it can be retrieved via API...

**Comment by SeverusYixin** [comment]
Hi @haesleinhuepf, I have a question, when submitting a url for a github rep, how should we define the type and tag? Or do we just leave them undefined?

Best regards,
Yixin

**Comment by haesleinhuepf** [comment]
I think we should write something in there, at least for the content type. Otherwise it wouldn't show up on the webpage. I asked git-bob what types other other github entries have: https://github.com/NFDI4BIOIMAGE/training/issues/299

**Comment by SeverusYixin** [comment]
> I think we should write something in there, at least for the content type. Otherwise it wouldn't show up on the webpage. I asked git-bob what types other github entries have: #299

Yes, that's why I'm asking you, because when I open the git repositories, I don't know where or what the types and tags definitions are. If I don't know them, I can't define them in the script.

And seems in the Zenodo links, also do not have types and tags definitions.

I will check them tomorrow and we can also discuss them, because I want to know the reasoning behind the classification of a "repo" as a type.

Btw, have a good evening ~
